"""What metaseed-hub imports from metaseed — the frozen consumer contract.

GENERATED by scripts/regenerate_hub_contract.py; do not edit by hand.
Regenerate after the hub adopts new metaseed surface. The contract test
resolves every entry, so renaming or deleting any of these breaks
metaseed's own CI rather than the hub's next upgrade (#70).
"""

HUB_IMPORTS: dict[str, list[str]] = {
    "metaseed": [
        "EntityNotFoundError",
        "MetaseedClient",
        "MetaseedError",
        "ProfileFacade",
        "SkippedNode",
        "adapters",
    ],
    "metaseed.adapters": ["Action"],
    "metaseed.agent.mcp.caller": ["current_request"],
    "metaseed.agent.mcp.server": ["SPEC_BUILDING_INSTRUCTIONS"],
    "metaseed.api.client": ["MetaseedClient"],
    "metaseed.facade": ["ProfileFacade"],
    "metaseed.repositories": ["AsyncDatasetRepository"],
    "metaseed.seek": [
        "build_provisioning_plan",
        "client_from_settings",
        "execute_provisioning_plan",
        "sync_dataset_to_seek",
    ],
    "metaseed.seek.provision": ["resolve_cv_ids"],
    "metaseed.seek.templates": ["template_title", "to_isa_template_json"],
    "metaseed.services": ["get_ontology_service"],
    "metaseed.services.ontology": ["OntologyServiceError"],
    "metaseed.services.term_check": ["ontology_of"],
    "metaseed.services.terms": ["get_term_source"],
    "metaseed.specs": [
        "compare_specs",
        "content_hash",
        "declared_bump",
        "required_bump",
        "short_hash",
    ],
    "metaseed.specs.builder": [
        "CONSTRAINT_NAMES",
        "FIELD_MARKER_NAMES",
        "RULE_ATTRIBUTE_NAMES",
        "SpecBuilder",
        "normalize_markers",
        "validate_constraint_names",
        "validate_marker_values",
    ],
    "metaseed.specs.loader": ["SpecLoader"],
    "metaseed.specs.merge": ["DiffVisualizer", "SpecComparator"],
    "metaseed.specs.schema": [
        "Constraints",
        "EntityDefSpec",
        "FieldSpec",
        "FieldType",
        "ProfileSpec",
        "ValidationRuleSpec",
    ],
    "metaseed.specs.versioning": [
        "HASH_ALGORITHM",
        "SHORT_HASH_DIGITS",
        "check_profile_version",
        "parse_profile_version",
    ],
    "metaseed.ui": [],
    "metaseed.ui.services.export": ["build_workbook_from_facade"],
    "metaseed.ui.state": ["AppState", "TreeNode"],
}
