"""Export a ``pride``-profile dataset to PRIDE submission artifacts.

Produces two tab-separated documents from a metaseed ``pride`` dataset, both
pure and dependency-free (stdlib only), never uploading anything (submission and
auth are out of scope):

* :func:`to_pride_submission` -- the ``submission.px`` document consumed by the
  ProteomeXchange ``px-submission-tool``. Data files are *referenced* by name
  and type in file-mapping (``FME``) lines.
* :func:`to_pride_sdrf` -- the SDRF-Proteomics sample-to-data table.
* :func:`to_pride_bundle` -- both of the above, since a submission needs both.

The format is tab-separated, one record per line, each prefixed by a line-type
token:

* ``MTD`` -- a metadata field (``MTD<TAB>key<TAB>value``).
* ``FME`` -- a file-mapping entry (``FME<TAB>file_id<TAB>file_type<TAB>file_path``).

This is the round-trip partner of :func:`metaseed.pride.import_accession`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from metaseed.api.client import MetaseedClient

_HEADER = "# PRIDE submission.px generated by metaseed"


def _dataset_with_children(client: MetaseedClient) -> dict[str, Any] | None:
    """The root Dataset dict with its child-node entities embedded by type.

    A pride dataset can be built two ways: authored/imported (the Dataset carries
    inline Species/Instrument/Sample/DataFile/... lists) or through the
    create-under-parent MCP flow (those are separate child nodes, per the MCP
    server's root-first instructions). This folds any child-node entities into
    their nested field by entity type -- the same reconstruction validation does
    -- so the exporters see the same shape either way. Inline lists are preserved
    and children appended, so a dataset built either way exports fully.

    Returns:
        The Dataset dict (a copy), or ``None`` when the client holds no Dataset.
    """
    entities = client.serialize()["entities"]
    datasets = [e for e in entities if e.get("_type") == "Dataset"]
    if not datasets:
        return None
    dataset = {
        key: list(value) if isinstance(value, list) else value
        for key, value in datasets[0].items()
    }

    try:
        helper = client.facade.get_helper("Dataset")
    except (KeyError, AttributeError):
        helper = None
    if helper is None:
        return dataset

    field_for_type: dict[str, str] = {}
    for field_name, entity_type in helper.nested_fields.items():
        field_for_type.setdefault(entity_type, field_name)

    by_node = {str(entity.get("_node_id")): entity for entity in entities}

    def descend(node: Any) -> None:
        for child in node.children:
            entity = by_node.get(str(child.id))
            target = field_for_type.get(child.entity_type)
            if entity is not None and target is not None:
                existing = dataset.get(target)
                if isinstance(existing, list):
                    existing.append(entity)
                else:
                    dataset[target] = [entity]
            descend(child)

    dataset_node_id = str(dataset.get("_node_id"))
    for root in client.get_tree():
        if str(root.id) == dataset_node_id:
            descend(root)
    return dataset


def _contact_by_role(contacts: list[dict[str, Any]], role: str) -> dict[str, Any]:
    """Return the first contact matching ``role`` (empty dict if none)."""
    for contact in contacts:
        if contact.get("role") == role:
            return contact
    return {}


def _mtd(key: str, value: Any) -> str | None:
    """Build an ``MTD`` line, or ``None`` when ``value`` is empty."""
    if value in (None, "", [], {}):
        return None
    return f"MTD\t{key}\t{value}"


def _metadata_lines(dataset: dict[str, Any]) -> list[str]:
    """Render the ``MTD`` metadata lines for a ``pride`` Dataset."""
    contacts = dataset.get("contacts") or []
    submitter = _contact_by_role(contacts, "submitter")
    lab_head = _contact_by_role(contacts, "lab head")
    keywords = dataset.get("keywords") or []

    candidates = [
        _mtd("submitter_name", submitter.get("name")),
        _mtd("submitter_email", submitter.get("email")),
        _mtd("submitter_affiliation", submitter.get("affiliation")),
        # PX uses the submitter email as the PRIDE login user name.
        _mtd("submitter_pride_login", submitter.get("email")),
        _mtd("lab_head_name", lab_head.get("name")),
        _mtd("lab_head_email", lab_head.get("email")),
        _mtd("lab_head_affiliation", lab_head.get("affiliation")),
        _mtd("project_title", dataset.get("title")),
        _mtd("project_description", dataset.get("description")),
        _mtd("keywords", ", ".join(str(k) for k in keywords)),
        _mtd("submission_type", dataset.get("submission_type")),
        _mtd("reason_for_partial", dataset.get("reason_for_partial")),
    ]
    for experiment_type in dataset.get("experiment_types") or []:
        candidates.append(_mtd("experiment_type", experiment_type))
    for species in dataset.get("species") or []:
        candidates.append(_mtd("species", species.get("name")))
    # PX requires tissue; emit each distinct sample tissue (order-preserving).
    seen_tissues: set[str] = set()
    for sample in dataset.get("samples") or []:
        tissue = sample.get("tissue")
        if tissue and tissue not in seen_tissues:
            seen_tissues.add(tissue)
            candidates.append(_mtd("tissue", tissue))
    for instrument in dataset.get("instruments") or []:
        candidates.append(_mtd("instrument", instrument.get("name")))
    for modification in dataset.get("modifications") or []:
        candidates.append(_mtd("modification", modification.get("name")))

    return [line for line in candidates if line is not None]


def _file_lines(dataset: dict[str, Any]) -> list[str]:
    """Render the ``FMH`` header and one ``FME`` entry per referenced data file.

    The PRIDE px file-mapping section is an ``FMH`` header row declaring the
    columns followed by ``FME`` rows ordered ``file_id, file_type, file_path``.
    """
    files = [f for f in (dataset.get("files") or []) if f.get("filename")]
    if not files:
        return []
    lines = ["FMH\tfile_id\tfile_type\tfile_path"]
    for file_id, file in enumerate(files):
        file_type = str(file.get("file_type") or "")
        path = str(file.get("filename"))
        lines.append(f"FME\t{file_id}\t{file_type}\t{path}")
    return lines


_NA = "not available"
# Fixed technology-type term for MS proteomics (PSI-MS wording used by SDRF).
_TECHNOLOGY_TYPE = "proteomic profiling by mass spectrometry"


def _characteristic_columns(samples: list[dict[str, Any]]) -> list[str]:
    """Return the ordered ``characteristics[...]`` column keys.

    A fixed core (organism, organism part, cell type, disease) is always
    present, followed by any custom-attribute names, in first-seen order, so
    every sample row shares the same columns.
    """
    columns = ["organism", "organism part", "cell type", "disease"]
    seen = set(columns)
    for sample in samples:
        for attr in sample.get("custom_attributes") or []:
            name = attr.get("name")
            if name and name not in seen:
                seen.add(name)
                columns.append(str(name))
    return columns


def _sample_characteristic(sample: dict[str, Any], key: str) -> str:
    """Resolve a single ``characteristics[key]`` value for a sample."""
    core = {
        "organism": sample.get("species"),
        "organism part": sample.get("tissue"),
        "cell type": sample.get("cell_type"),
        "disease": sample.get("disease"),
    }
    if key in core:
        return str(core[key]) if core[key] else _NA
    for attr in sample.get("custom_attributes") or []:
        if attr.get("name") == key:
            return str(attr.get("value")) if attr.get("value") else _NA
    return _NA


def _files_for_sample(
    sample: dict[str, Any], files: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    """Return the data files that reference ``sample`` by name."""
    name = sample.get("name")
    matched = [f for f in files if name in (f.get("sample_refs") or [])]
    return matched


def to_pride_sdrf(client: MetaseedClient) -> dict[str, str]:
    """Render a ``pride``-profile dataset as an SDRF-Proteomics table.

    SDRF-Proteomics is a tab-separated sample-to-data table: one row per
    (sample, data file) pair. Columns are ``source name``, the
    ``characteristics[...]`` sample columns, ``assay name``, ``technology
    type``, and the ``comment[...]`` columns (data file, instrument). Missing
    values render as ``"not available"`` per SDRF convention.

    Args:
        client: A MetaseedClient bound to the ``pride`` profile whose root
            Dataset carries the nested Sample and DataFile lists. A sample is
            linked to a file via the file's ``sample_refs`` (sample names).

    Returns:
        Mapping ``{"sdrf.tsv": ...}``. Empty when the dataset holds no samples
        (the PRIDE Archive API exposes no per-sample rows, so an imported-only
        dataset has none to export).
    """
    dataset = _dataset_with_children(client)
    if dataset is None:
        return {}
    samples = dataset.get("samples") or []
    if not samples:
        return {}

    files = dataset.get("files") or []
    instruments = dataset.get("instruments") or []
    instrument = str(instruments[0].get("name")) if instruments else _NA

    char_cols = _characteristic_columns(samples)
    header = (
        ["source name"]
        + [f"characteristics[{c}]" for c in char_cols]
        + ["assay name", "technology type", "comment[data file]", "comment[instrument]"]
    )

    rows = [header]
    assay_index = 0
    for sample in samples:
        chars = [_sample_characteristic(sample, c) for c in char_cols]
        # One row per associated file; a sample with no files still gets a row.
        matched = _files_for_sample(sample, files)
        sample_files: list[dict[str, Any] | None] = list(matched) if matched else [None]
        for data_file in sample_files:
            assay_index += 1
            data_name = (
                str(data_file.get("filename"))
                if data_file and data_file.get("filename")
                else _NA
            )
            rows.append(
                [
                    str(sample.get("name") or _NA),
                    *chars,
                    f"run {assay_index}",
                    _TECHNOLOGY_TYPE,
                    data_name,
                    instrument,
                ]
            )

    text = "\n".join("\t".join(row) for row in rows) + "\n"
    return {"sdrf.tsv": text}


def to_pride_submission(client: MetaseedClient) -> dict[str, str]:
    """Render a ``pride``-profile dataset as a PRIDE ``submission.px`` file.

    Args:
        client: A MetaseedClient bound to the ``pride`` profile. Its single root
            ``Dataset`` carries the nested Species, Instrument, Modification,
            Contact, and DataFile lists.

    Returns:
        Mapping of document name to text, i.e. ``{"submission.px": ...}``. Empty
        when the client holds no Dataset.
    """
    dataset = _dataset_with_children(client)
    if dataset is None:
        return {}

    lines = [_HEADER, *_metadata_lines(dataset), *_file_lines(dataset)]
    return {"submission.px": "\n".join(lines) + "\n"}


def to_pride_bundle(client: MetaseedClient) -> dict[str, str]:
    """Render both PRIDE submission documents together.

    A ProteomeXchange submission consists of the ``submission.px`` file *and*
    its SDRF sample table, so they are one deliverable rather than two
    alternatives. This is the form the adapter registry declares, letting a host
    offer a single download holding both.

    Args:
        client: A MetaseedClient bound to the ``pride`` profile.

    Returns:
        Mapping of document name to text, holding ``submission.px`` and
        ``sdrf.tsv``. The SDRF is absent when the dataset has no samples (an
        imported-only dataset), so a header-only table is never shipped. Empty
        when the client holds no Dataset.
    """
    return {**to_pride_submission(client), **to_pride_sdrf(client)}
