"""Export a ``pride``-profile dataset to a PRIDE ``submission.px`` file.

Produces the ``submission.px`` document consumed by the ProteomeXchange
``px-submission-tool`` from a metaseed ``pride`` dataset. Pure and
dependency-free (stdlib only). Data files are *referenced* by name and type in
file-mapping (``FME``) lines; this never uploads anything (submission/auth is
out of scope).

The format is tab-separated, one record per line, each prefixed by a line-type
token:

* ``MTD`` -- a metadata field (``MTD<TAB>key<TAB>value``).
* ``FME`` -- a file-mapping entry (``FME<TAB>index<TAB>filename<TAB>type``).

This is the round-trip partner of :func:`metaseed.pride.import_accession`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from metaseed.api.client import MetaseedClient

_HEADER = "# PRIDE submission.px generated by metaseed"


def _contact_by_role(contacts: list[dict[str, Any]], role: str) -> dict[str, Any]:
    """Return the first contact matching ``role`` (empty dict if none)."""
    for contact in contacts:
        if contact.get("role") == role:
            return contact
    return {}


def _mtd(key: str, value: Any) -> str | None:
    """Build an ``MTD`` line, or ``None`` when ``value`` is empty."""
    if value in (None, "", [], {}):
        return None
    return f"MTD\t{key}\t{value}"


def _metadata_lines(dataset: dict[str, Any]) -> list[str]:
    """Render the ``MTD`` metadata lines for a ``pride`` Dataset."""
    contacts = dataset.get("contacts") or []
    submitter = _contact_by_role(contacts, "submitter")
    lab_head = _contact_by_role(contacts, "lab head")
    keywords = dataset.get("keywords") or []

    candidates = [
        _mtd("submitter_name", submitter.get("name")),
        _mtd("submitter_email", submitter.get("email")),
        _mtd("submitter_affiliation", submitter.get("affiliation")),
        _mtd("lab_head_name", lab_head.get("name")),
        _mtd("lab_head_email", lab_head.get("email")),
        _mtd("lab_head_affiliation", lab_head.get("affiliation")),
        _mtd("project_title", dataset.get("title")),
        _mtd("project_description", dataset.get("description")),
        _mtd("keywords", ", ".join(str(k) for k in keywords)),
        _mtd("submission_type", dataset.get("submission_type")),
    ]
    for species in dataset.get("species") or []:
        candidates.append(_mtd("species", species.get("name")))
    for instrument in dataset.get("instruments") or []:
        candidates.append(_mtd("instrument", instrument.get("name")))
    for modification in dataset.get("modifications") or []:
        candidates.append(_mtd("modification", modification.get("name")))

    return [line for line in candidates if line is not None]


def _file_lines(dataset: dict[str, Any]) -> list[str]:
    """Render the ``FMH`` header and one ``FME`` entry per referenced data file.

    The PRIDE px file-mapping section is an ``FMH`` header row declaring the
    columns followed by ``FME`` rows ordered ``file_id, file_type, file_path``.
    """
    files = [f for f in (dataset.get("files") or []) if f.get("filename")]
    if not files:
        return []
    lines = ["FMH\tfile_id\tfile_type\tfile_path"]
    for file_id, file in enumerate(files):
        file_type = str(file.get("file_type") or "")
        path = str(file.get("filename"))
        lines.append(f"FME\t{file_id}\t{file_type}\t{path}")
    return lines


def to_pride_submission(client: MetaseedClient) -> dict[str, str]:
    """Render a ``pride``-profile dataset as a PRIDE ``submission.px`` file.

    Args:
        client: A MetaseedClient bound to the ``pride`` profile. Its single root
            ``Dataset`` carries the nested Species, Instrument, Modification,
            Contact, and DataFile lists.

    Returns:
        Mapping of document name to text, i.e. ``{"submission.px": ...}``. Empty
        when the client holds no Dataset.
    """
    entities = client.serialize()["entities"]
    datasets = [e for e in entities if e.get("_type") == "Dataset"]
    if not datasets:
        return {}
    dataset = datasets[0]

    lines = [_HEADER, *_metadata_lines(dataset), *_file_lines(dataset)]
    return {"submission.px": "\n".join(lines) + "\n"}
