"""Regenerate the hub-contract inventory from a metaseed-hub checkout.

The hub is metaseed's sole external consumer, and the rule 'check the hub
before renaming a public symbol' was informal. This script freezes what the
hub imports into tests/hub_contract.py; the contract test resolves every
entry, so a rename that would break the hub turns metaseed's own CI red
before a release (#70).

Usage:
    uv run python scripts/regenerate_hub_contract.py [path-to-metaseed-hub]
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path


def hub_imports(hub_src: Path) -> dict[str, set[str]]:
    """Map metaseed module path -> symbols the hub imports from it."""
    imports: dict[str, set[str]] = {}
    for path in sorted(hub_src.rglob("*.py")):
        tree = ast.parse(path.read_text(), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module:
                if node.module == "metaseed" or node.module.startswith("metaseed."):
                    names = imports.setdefault(node.module, set())
                    for alias in node.names:
                        names.add(alias.name)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "metaseed" or alias.name.startswith("metaseed."):
                        imports.setdefault(alias.name, set())
    return imports


def main() -> None:
    hub = Path(sys.argv[1] if len(sys.argv) > 1 else "../metaseed-hub")
    src = hub / "src" / "metaseed_hub"
    if not src.is_dir():
        raise SystemExit(f"not a metaseed-hub checkout: {hub}")

    imports = hub_imports(src)
    out = Path(__file__).parent.parent / "tests" / "hub_contract.py"
    lines = [
        '"""What metaseed-hub imports from metaseed — the frozen consumer contract.',
        "",
        "GENERATED by scripts/regenerate_hub_contract.py; do not edit by hand.",
        "Regenerate after the hub adopts new metaseed surface. The contract test",
        "resolves every entry, so renaming or deleting any of these breaks",
        "metaseed's own CI rather than the hub's next upgrade (#70).",
        '"""',
        "",
        "HUB_IMPORTS: dict[str, list[str]] = {",
    ]
    for module in sorted(imports):
        symbols = sorted(imports[module])
        lines.append(f"    {module!r}: {symbols!r},")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n")
    total = sum(len(v) for v in imports.values())
    print(f"{out}: {len(imports)} modules, {total} symbols")


if __name__ == "__main__":
    main()
